AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  RouterLambdaName:
    Type: String
    Default: abtesting_router
    Description: |
      The name for the Lambda function that serves as the router.
    AllowedPattern: '([a-zA-Z0-9-_]+)'
    ConstraintDescription: >
      Must be a valid Lambda name, i.e. between 1 and 140 letters,
      and contain only alphanumeric characters, hyphens and underscores
    MinLength: 1
    MaxLength: 140
  RouterLambdaTestingSalt:
    Type: String
    Default: "A/B-testing rocks!"
    Description: >
      A random piece of text that is used as a salt for the hash function that assigns
      users to test groups. Must remain constant within each test, but differ between
      tests to ensure users will get re-assigned randomly.
    MinLength: 1
    MaxLength: 140
  RouterLambdaTestingSplit:
    Type: String
    Default: "50,50"
    Description: |
      The comma-separated list of integer percentage values for test groups A, B, C, etc.
    AllowedPattern: '^\s*(\d{1,3})?\s*(,\s*\d{1,2})*\s*$'
    ConstraintDescription: Must adhere to the pattern ^\s*(\d{1,3})?\s*(,\s*\d{1,2})*\s*$
  RouterLambdaTimeout:
    Type: Number
    Default: 6
    Description: |
      The tiemout for the Router Lambda function in seconds
    MinValue: 3
    MaxValue: 8
  ResultDynamoDBTableName:
    Type: String
    Default: abtesting_results
    Description: |
      Database for storing observations for the A/B-test
    AllowedPattern: '[a-zA-Z0-9_.-]+'
    ConstraintDescription: >
      Must be a valid DynamoDB name, i.e. between 3 and 255 letters,
      and contain only alphanumeric characters, hyphens, underscores and periods
    MinLength: 3
    MaxLength: 255
  ResultDynamoDBBillingMode:
    Type: String
    Default: PROVISIONED
    Description: >
      Billing mode for your DynamoDB table. 'PROVISIONED' is eligible for the AWS free tier,
      and will reserve 1 capacity unit for reading and writing. 'PAY_PER_REQUEST' enables
      on-demand scaling and billing.
    AllowedValues:
      - PROVISIONED
      - PAY_PER_REQUEST
  VersionLambdaNameA:
    Type: String
    Default: abtesting_version_a
    Description: |
      The name for the Lambda function that executes version A.
    AllowedPattern: '([a-zA-Z0-9-_]+)'
    ConstraintDescription: >
      Must be a valid Lambda name, i.e. between 1 and 140 letters,
      and contain only alphanumeric characters, hyphens and underscores
    MinLength: 1
    MaxLength: 140
  VersionLambdaNameB:
    Type: String
    Default: abtesting_version_b
    Description: |
      The name for the Lambda function that executes version B.
    AllowedPattern: '([a-zA-Z0-9-_]+)'
    ConstraintDescription: >
      Must be a valid Lambda name, i.e. between 1 and 140 letters,
      and contain only alphanumeric characters, hyphens and underscores
    MinLength: 1
    MaxLength: 140
  VersionLambdaTimeout:
    Type: Number
    Default: 4
    Description: |
      The tiemout for the Versions' Lambda functions in seconds
    MinValue: 3
    MaxValue: 8
Outputs:
  EndpointARN:
    Description: The endpoint ARN to be used in the Alexa Skill manifest
    Value: !GetAtt
      - RouterLambda
      - Arn
Conditions:
  isDynamoDBProvisioned: !Equals [ !Ref ResultDynamoDBBillingMode, PROVISIONED ]
Resources:
  RouterPolicy:
    Type: AWS::IAM::Policy
    DependsOn:
      - RouterRole
      - VersionLambdaA
      - VersionLambdaA
    Properties:
      PolicyName: ABTestingRouterPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup*
              - logs:CreateLogStream*
              - logs:PutLogEvents*
            Resource: !Join
              - ""
              - - "arn:aws:logs:"
                - !Ref "AWS::Region"
                - ":"
                - !Ref "AWS::AccountId"
                - ":log-group:"
                - !Ref RouterLambdaName
                - ":*:*"
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource:
              - !GetAtt
                - VersionLambdaA
                - Arn
              - !GetAtt
                - VersionLambdaB
                - Arn
      Roles:
        - ABTestingRouterRole
  RouterRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: ABTestingRouterRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com" 
            Action: 
              - "sts:AssumeRole"
  RouterLambda:
    Type: AWS::Lambda::Function
    DependsOn:
      - RouterPolicy
      - VersionLambdaA
      - VersionLambdaB
    Properties: 
      FunctionName: !Ref RouterLambdaName
      Code: 
        S3Bucket: alexaskill-abtesting-poc
        S3Key: "router.zip"
      Description: >
        The Router component of the A/B-Testing system. Consistently assigns users to
        a test group, and invokes the corresponding version's Lambda function with the
        request that it received from Alexa.
      Environment: 
        Variables: 
          TESTING_SALT: !Ref RouterLambdaTestingSalt
          TESTING_SPLIT: !Ref RouterLambdaTestingSplit
          LAMBDA_ARN_VERSION_A: !GetAtt
            - VersionLambdaA
            - Arn
          LAMBDA_ARN_VERSION_B: !GetAtt
            - VersionLambdaB
            - Arn
      Handler: index.handler
      MemorySize: 128
      Role: !GetAtt
        - RouterRole
        - Arn
      Runtime: "nodejs10.x"
      Timeout: !Ref RouterLambdaTimeout
  RouterAlexaTriggerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        !Ref RouterLambda
      Action: "lambda:InvokeFunction"
      Principal: "alexa-appkit.amazon.com"
  ResultStore:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: !Ref ResultDynamoDBTableName
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      BillingMode: !Ref ResultDynamoDBBillingMode
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput: !If
        - isDynamoDBProvisioned
        - ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        - Ref: AWS::NoValue
  VersionPolicy:
    Type: AWS::IAM::Policy
    DependsOn:
      - VersionRole
      - ResultStore
    Properties:
      PolicyName: ABTestingVersionPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup*
              - logs:CreateLogStream*
              - logs:PutLogEvents*
            Resource: 
              - !Join
                - ""
                - - "arn:aws:logs:"
                  - !Ref "AWS::Region"
                  - ":"
                  - !Ref "AWS::AccountId"
                  - ":log-group:"
                  - !Ref VersionLambdaNameA
                  - ":*:*"
              - !Join
                - ""
                - - "arn:aws:logs:"
                  - !Ref "AWS::Region"
                  - ":"
                  - !Ref "AWS::AccountId"
                  - ":log-group:"
                  - !Ref VersionLambdaNameB
                  - ":*:*"
          - Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource: !GetAtt
              - ResultStore
              - Arn
      Roles:
        - ABTestingVersionRole
  VersionRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: ABTestingVersionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "lambda.amazonaws.com" 
            Action: 
              - "sts:AssumeRole"
  VersionLambdaA:
    Type: AWS::Lambda::Function
    DependsOn: VersionPolicy
    Properties: 
      FunctionName: !Ref VersionLambdaNameA
      Code: 
        S3Bucket: alexaskill-abtesting-poc
        S3Key: "version.zip"
      Description: >
        The Version A Lambda component of the A/B-Testing system. Generates the response
        for the user, measures target metrics for the A/B-test, and writes them into the result store.
      Environment: 
        Variables: 
          DYNAMODB_TABLE_NAME: !Ref ResultStore
          TESTING_CONTENT: A
      Handler: index.handler
      MemorySize: 128
      Role: !GetAtt
        - VersionRole
        - Arn
      Runtime: "nodejs10.x"
      Timeout: !Ref VersionLambdaTimeout
  VersionLambdaB:
    Type: AWS::Lambda::Function
    DependsOn: VersionPolicy
    Properties: 
      FunctionName: !Ref VersionLambdaNameB
      Code: 
        S3Bucket: alexaskill-abtesting-poc
        S3Key: "version.zip"
      Description: >
        The Version B Lambda component of the A/B-Testing system. Generates the response
        for the user, measures target metrics for the A/B-test, and writes them into the result store.
      Environment: 
        Variables: 
          DYNAMODB_TABLE_NAME: !Ref ResultStore
          TESTING_CONTENT: B
      Handler: index.handler
      MemorySize: 128
      Role: !GetAtt
        - VersionRole
        - Arn
      Runtime: "nodejs10.x"
      Timeout: !Ref VersionLambdaTimeout